#' @title Measuring matrix similarities
#' @description This script measures the similarities between the matrices
#' generated by the different iterations and nested seeds of the fastspar
#' algorithm.
#' @author Brait LAS.
#' @date july 2023.
#' @reviewer None.

################################# Environment ##################################
options(scipen = 9999999)
options(digits = 20)

source("R/src/install_and_load.R")
install_and_load(
  libs = c(
    "tidyverse" = "any",
    "stringr" = "any",
    "ggpubr" = "0.2.4",
    "cowplot" = "0.9.4"
  )
)
source("R/src/calculate_cosine_similarity.R")
source("R/src/convert_matrix_tonumeric.R")

if (interactive()) {
  analysis_frame <- "phyla_analysis_july23"
} else {
  args <- commandArgs(trailingOnly = TRUE)
  analysis_frame <- as.character(args[1])
}

summary_path <- paste0(
    "data/", analysis_frame, "/summaries/performance_fastspar_iterations/")
plot_path <- paste0(
    "results/", analysis_frame, "/performance_fastspar_iterations/")

if (!file.exists("results/")) {
  dir.create("results/")
  }

if (!file.exists(summary_path)) {
    dir.create(summary_path)
  }

if (!file.exists(plot_path)) {
    dir.create(plot_path)
  }


habitats <- dir(paste0(
  "data/", analysis_frame, "/performance_fastspar_iterations/"),
  full.names = TRUE)


data_frames <- list()
results_df <- data.frame()


for (habitat_path in habitats){

  habitat_name <- basename(habitat_path)
  print(paste0("processing: ", habitat_name))

  if (file.exists(
    paste0(summary_path, habitat_name,".csv"))){
    print(paste0("skipping: ", habitat_name))

  } else {

  #intialized the data frame of the habitat results
  habitat_data_frame <- data.frame()

  #order the iterations ascendingly
  iterations <- dir(habitat_path, full.names = TRUE)

  orderer <- as.numeric(str_extract(iterations, "\\d+"))
  iterations <- iterations[order(orderer)]

  #get iteration folders
  for (iteration_path in iterations){

  iteration_name <- basename(iteration_path)
  print(paste0(
    "checking results for: ", habitat_name, "iteration: ", iteration_name))

  #get the tables
  tables <- dir(iteration_path, pattern = "cor_", full.names = TRUE)

  orderer <- as.numeric(str_extract(tables, "\\d+"))
  tables <- tables[order(orderer)]

  matrices <- list()


    for (table_path in tables){

      table_name <- basename(table_path)
      print(paste0("table: ", table_name))
      table_name <- basename(table_path)

      #treat from df to matrix
      table <- as.matrix(read_tsv(table_path, show_col_types = FALSE))
      table <- as.data.frame(table)
      table[1] <- NULL
      colnames(table) <- NULL
      table <- convert_matrix_tonumeric(table)
      table <- as.matrix(table)

      #store the matrix
      matrices[[table_name]] <- table

    }

  results_similarities <- compute_matrices_similarity(matrices)
  results_similarities <- as.vector(
    results_similarities[upper.tri(results_similarities, diag = FALSE)])

  results_df_parcial <- data.frame(iteration_name = results_similarities)
  colnames(results_df_parcial) <- c(iteration_name)

  #This prevents an error while binding the data frames
  if (nrow(results_df) == 0) {
       results_df <- results_df_parcial
   } else {
       results_df <- cbind(results_df, results_df_parcial)
   }

  }


  write.csv(
    results_df,
    paste0(summary_path, habitat_name, ".csv"),
    row.names = FALSE)


  results_df <- data.frame()

   }
}
